PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "Mom: …Right.\n"
    .string "All boys leave home someday.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "Mom: …Right.\n"
    .string "All girls dream of traveling.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "Mom: {PLAYER}!\n"
    .string "You should take a quick rest.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "Mom: Oh, good! You and your\n"
    .string "POKéMON are looking great.\l"
    .string "Take care now!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "There's a movie on TV.\n"
    .string "Four boys are walking on railroad\l"
    .string "tracks.\p"
    .string "…I better go, too.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "There's a movie on TV.\n"
    .string "A girl with her hair in pigtails is\l"
    .string "walking up a brick road.\p"
    .string "…I better go, too.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Oops, wrong side…$"

PalletTown_PlayersHouse_1F_Text_MomRunningShoes1::
    .string "Mom: Oh! I almost forgot!\p"
    .string "I bought you a pair of Running Shoes\n"
    .string "for you to wear on your adventure!$"

PalletTown_PlayersHouse_1F_Text_MomRunningShoes2::
    .string "Mom: Just hold the B Button to run.\p"
    .string "...\p"
    .string "Well I suppose you'd better head\n"
    .string "out now.\p"
    .string "I'll see you around!\p$"

PalletTown_PlayersHouse_1F_Text_TriedOnRunningShoes::
    .string "{PLAYER} tried on the Running Shoes!\p"
    .string "They fit nice and snug.$"
